##
# Файл для хранения общих данных приложения
# Нельзя удалять, менять ключи, или добавлять новые значения в файл
#
# Префикс: `app`
# Использование: `{{ app.name }}`
#
# Можно использовать переменные из app.yml
#
# Заполняется один раз при старте приложения
##

name: 'FaithNode'
navTitle: 'Вики {{ app.name }}'
url: 'https://faithnode.host'
createdAt: '2021-05-11'
